url: https://y7kim.github.io
baseurl: 

# Site settings
title: Aditya Rathi
email: rathi.aditya@iitgn.ac.in
description: "Aditya Rathi is a senior undergraduate in mechanical engineering at IIT Gandhinagar."



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/rathi-aditya/
  - title: facebook
    url: https://www.facebook.com/adityamrathi
  - title: instagram
    url: https://www.instagram.com/adityarathi14/
  - title: github
    url: https://github.com/aditya-rathi
  - title: envelope-o
    url: mailto:rathi.aditya@iitgn.ac.in

# Postal address (add as many lines as necessary)
#address:
 # - line: 3481 Melrose Place
  #- line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty